INSERT INTO SystemeJeu (%PARAM_COLONNES%) VALUES (%PARAM_VALUES%);

INSERT INTO SystemeJeu (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO PartieCorps (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO Race (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO Metier (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO Classe (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO TypeObjet (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO Objet (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

INSERT INTO Caracteristique (%PARAM_COLONNES%) WHERE (%PARAM_VALUES%);

