UPDATE Intro SET contenu="%PARAM_CONTENU%" WHERE id=%PARAM_ID%;
UPDATE Description SET contenu="%PARAM_CONTENU%" WHERE id=%PARAM_ID%;

UPDATE Evenement SET intro=%PARAM_INTRO% WHERE intro=%PARAM_INTRO% AND description=%PARAM_DESCRIPTION%;
UPDATE Evenement SET intro=%PARAM_INTRO% WHERE intro=%PARAM_INTRO%;
UPDATE Evenement SET intro=%PARAM_INTRO% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Evenement SET description=%PARAM_DESCRIPTION% WHERE intro=%PARAM_INTRO% AND description=%PARAM_DESCRIPTION%;
UPDATE Evenement SET description=%PARAM_DESCRIPTION% WHERE intro=%PARAM_INTRO%;
UPDATE Evenement SET description=%PARAM_DESCRIPTION% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Evenement SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION% WHERE description=%PARAM_DESCRIPTION%;


UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE id=%PARAM_ID%;
UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION% WHERE id=%PARAM_ID%;
UPDATE Choix SET intro=%PARAM_INTRO%, parent=%PARAM_PARENT% WHERE id=%PARAM_ID%;
UPDATE Choix SET description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE id=%PARAM_ID%;
UPDATE Choix SET intro=%PARAM_INTRO% WHERE id=%PARAM_ID%;
UPDATE Choix SET description=%PARAM_DESCRIPTION% WHERE id=%PARAM_ID%;
UPDATE Choix SET parent=%PARAM_PARENT% WHERE id=%PARAM_ID%;

UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET intro=%PARAM_INTRO%, parent=%PARAM_PARENT% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET intro=%PARAM_INTRO% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET description=%PARAM_DESCRIPTION% WHERE intro=%PARAM_INTRO%;
UPDATE Choix SET parent=%PARAM_PARENT% WHERE intro=%PARAM_INTRO%;

UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET intro=%PARAM_INTRO%, parent=%PARAM_PARENT% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET intro=%PARAM_INTRO% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET description=%PARAM_DESCRIPTION% WHERE description=%PARAM_DESCRIPTION%;
UPDATE Choix SET parent=%PARAM_PARENT% WHERE description=%PARAM_DESCRIPTION%;

UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET intro=%PARAM_INTRO%, description=%PARAM_DESCRIPTION% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET intro=%PARAM_INTRO%, parent=%PARAM_PARENT% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET description=%PARAM_DESCRIPTION%, parent=%PARAM_PARENT% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET intro=%PARAM_INTRO% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET description=%PARAM_DESCRIPTION% WHERE parent=%PARAM_PARENT%;
UPDATE Choix SET parent=%PARAM_PARENT% WHERE parent=%PARAM_PARENT%;


UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;
UPDATE Scenario SET debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%" AND debut=%PARAM_DEBUT%;

UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", debut=%PARAM_DEBUT% WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET auteur="%PARAM_AUTEUR%" WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET titre="%PARAM_TITRE%" WHERE debut=%PARAM_DEBUT%;
UPDATE Scenario SET debut=%PARAM_DEBUT% WHERE debut=%PARAM_DEBUT%;

UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET auteur="%PARAM_AUTEUR%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET titre="%PARAM_TITRE%", debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET auteur="%PARAM_AUTEUR%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Scenario SET debut=%PARAM_DEBUT% WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";


UPDATE Histoire SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Histoire SET auteur="%PARAM_AUTEUR%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Histoire SET titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%" AND titre="%PARAM_TITRE%";
UPDATE Histoire SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE titre="%PARAM_TITRE%";
UPDATE Histoire SET auteur="%PARAM_AUTEUR%" WHERE titre="%PARAM_TITRE%";
UPDATE Histoire SET titre="%PARAM_TITRE%" WHERE titre="%PARAM_TITRE%";
UPDATE Histoire SET auteur="%PARAM_AUTEUR%", titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%";
UPDATE Histoire SET auteur="%PARAM_AUTEUR%" WHERE auteur="%PARAM_AUTEUR%";
UPDATE Histoire SET titre="%PARAM_TITRE%" WHERE auteur="%PARAM_AUTEUR%";
